### ISSUE TITLE
Warnings "Request failed with status code 502/504"

### ISSUE THREAD

**Issue by Draexl** [mrbungle64/ioBroker.ecovacs-deebot#412] opened 2022-12-24 10:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

I found this messages in my Log

```
2022-12-24 09:43:11.062 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetPos
2022-12-24 09:48:08.146 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetPos
2022-12-24 09:57:08.253 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetCleanSum
2022-12-24 10:08:05.171 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 504 for command GetCleanSum
2022-12-24 10:40:08.783 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetSleepStatus
2022-12-24 10:53:05.606 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetCleanSum
2022-12-24 11:05:14.763 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetCleanSpeed
2022-12-24 11:08:05.672 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetCleanSpeed
2022-12-24 11:09:08.039 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetCleanState
2022-12-24 11:15:08.794 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetSleepStatus
2022-12-24 11:19:08.263 - warn: ecovacs-deebot.0 (10736) Error message received: Received error message: Request failed with status code 502 for command GetCleanSum
```

Version v1.4.8
Model: DEEBOT 710

### With which model does the problem occur?

Deebot 710/711/711s

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

 v1.4.8

### Version of the ecovacs-deebot.js library ("info.library.version")

0.9.0-beta.2

### Version of the JS controller

4.0.23

### Version of Node.js

v16.19.0

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
-
```

### Additional information

-

### Which "other" models are you using?

-

### Ecovacs device class ("info.deviceClass")

-

### Communication protocol ("info.library.communicationProtocol")

None

### Is the canvas module installed? ("info.library.canvasModuleIsInstalled")

None

**Comment by mrbungle64** [comment] 2022-12-24 10:38
@Draexl 

Currently, this happens more often.

Useful links:

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504

**Comment by mrbungle64** [comment] 2022-12-24 12:29
@Draexl 

In Deebot 4 Home Assistant I also get similar errors today:

```
Logger: deebot_client._api_client
Source: runner.py:120
First occurred: 13:20:28 (1 occurrences)
Last logged: 13:20:28

Error calling API (504): https://portal-eu.ecouser.net/api/iot/devmanager.do
```

```
Logger: deebot_client.commands.common
Source: runner.py:120
First occurred: 13:10:00 (92 occurrences)
Last logged: 13:24:11

Command "getCachedMapInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getSpeed" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getStats" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getPos" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Command "getChargeState" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

**Comment by mrbungle64** [comment] 2022-12-24 13:39
@Draexl 

`portal-eu.ecouser.net` seems to be down now.
The mobile app also shows "timeout" message.

**Comment by mrbungle64** [comment] 2022-12-24 20:48
> @Draexl
> 
> `portal-eu.ecouser.net` seems to be down now. The mobile app also shows "timeout" message.
> 
> Can you confirm this?

This problem seems to be solved now, after I restarted the robots 😉

**Comment by mrbungle64** [comment] 2022-12-25 20:00
@Draexl 

I still get several timeouts per day, but I think that we have to be patient until Ecovacs takes care of it ...

**Comment by Bullet586** [comment] 2022-12-27 10:39
Version v1.4.8
Model: DEEBOT 850

With which model does the problem occur?
Deebot 850

From which source you have installed the adapter?
Stable (default)

Version of the ioBroker adapter ("info.version")
v6.3.5

Version of the ecovacs-deebot.js library ("info.library.version")
0.9.0-beta.2

Version of the JS controller
4.0.23

Version of Node.js
v16.19.0

Operating system
Linux

Same Problem from my side, the alerts began a few days ago.

![image](https://user-images.githubusercontent.com/120199755/209654285-9b627a94-5fad-419c-887c-86c88ac76295.png)

Does anybody know is that a problem vom the evovacs server or from the adapter??

Best Regards

**Comment by mrbungle64** [comment] 2022-12-27 19:24
_"... **a 502/504 error is usually not something you can fix**, **but requires a fix by the web server or the proxies** ..."_

_502 Bad Gateway
The HyperText Transfer Protocol (HTTP) 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server._

_504 Gateway Timeout
The HyperText Transfer Protocol (HTTP) 504 Gateway Timeout server error response code indicates that the server, while acting as a gateway or proxy, did not get a response in time from the upstream server that it needed in order to complete the request._

_Note: A Gateway might refer to different things in networking and a 502/504 error is usually not something you can fix, but requires a fix by the web server or the proxies you are trying to get access through._

Sources (which I had already linked above):
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504

@Bullet586 
> Does anybody know is that a problem from the evovacs server or from the adapter??

It is very unlikely that this error messages are caused by the adapter.

Btw.: Do you really own a Deebot 850?

**Comment by Bullet586** [comment] 2022-12-27 19:30
No sorry my bad, you are right! It's an ECOVACS DEEBOT OZMO 950

**Comment by mrbungle64** [comment] 2022-12-27 19:41
To make it a little clearer, the warning messages say:

- this part means that the adapter (via underlying library) received an error message:
_"Error message received: [ Received error message ... ]"_
- followed by the actual error message:
_"Request failed with status code 504 for command getSleep"_

That means that a "502 Bad Gateway" or "504 Gateway Timeout" occurred on the server side when (in this example) the "getSleep" command was executed.

**Comment by mrbungle64** [comment] 2022-12-27 19:42
@Bullet586 

> I thought there is something wrong on my system.

No, you're "not alone" 😉

**Comment by krobipd** [comment] 2022-12-28 13:42
hey, I have the same "problems" everything works fine but the log is filling with this messages. ozmo 950 ;-)

**Comment by mrbungle64** [comment] 2022-12-28 21:44
@krobipd 

You can set the interval ("Abfrage-Intervall (Sekunden)") to 600 seconds if you use the Ecovacs mobile app only rarely.

**Comment by mrbungle64** [comment] 2022-12-30 16:09
@krobipd @Draexl @Bullet586

Do any of you still have warning messages?
I think that Ecovacs has fixed the hiccups...

**Comment by krobipd** [comment] 2022-12-30 16:23
> @krobipd @Draexl @Bullet586
> 
> Do any of you still have warning messages? I think that Ecovacs has fixed the hiccups...

today only in the very early hours. (0-1 am). nothing since then.

**Comment by Bullet586** [comment] 2022-12-30 17:46
No warnings anymore (at the moment) 👍🏻

**Comment by mrbungle64** [comment] 2022-12-30 18:11
@Draexl 

Please close this issue if you have no more warnings either.

**Comment by Draexl** [comment] 2022-12-30 18:13
All fine, thanks

**Closed** 2022-12-30 18:12 UTC
Labels: Verification
